name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: "@insertcoinab"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn publish

      - name: Notify Dependabot
        env:
          GITHUB_PAT: ${{ secrets.GWENNIFER_GITHUB_PAT }}
        run: |
          PACKAGE_VERSION=${GITHUB_REF/refs\/tags\/v}

          curl -s --request POST \
            --url https://api.dependabot.com/release_notifications/private \
            --header "Authorization: Personal $GITHUB_PAT" \
            --header 'content-type: application/json' \
            --data "{\"name\":\"@insertcoinab/gwen-react-components\",\"version\":\"$PACKAGE_VERSION\",\"package-manager\":\"npm_and_yarn\"}"
